services:
  marzafood-web:
    image: nginx:alpine
    container_name: marzafood-web
    restart: unless-stopped
    volumes:
      - ./site:/usr/share/nginx/html:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.marzafood.rule=Host(`${MARZAFOOD_DOMAIN}`)
      - traefik.http.routers.marzafood.entrypoints=websecure
      - traefik.http.routers.marzafood.tls=true
      - traefik.http.services.marzafood.loadbalancer.server.port=80
      - traefik.http.routers.marzafood.tls.certresolver=httpresolver

networks:
  proxy:
    external: true
